### ISSUE TITLE
Fingerprint protection

### ISSUE THREAD

**Issue by gameb0y** [kura52/sushi-browser#11]
can you add?

AudioContext Fingerprint
https://audiofingerprint.openwpm.com/

webgl
https://browserleaks.com/webgl

WebRTC Leak and unique devices id's
https://browserleaks.com/webrtc

Canvas
https://browserleaks.com/canvas

Battery Status API
https://browserleaks.com/javascript

**Comment by kura52** [comment]
Thank you for raising this issue.
I implement it in  [v0.11.0](https://github.com/kura52/sushi-browser/releases/tag/0.11.0).

Since this function has diverted the function of brave browser, please refer to the following for details.
https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode

![screenshot-2017-12-02 06-32-49](https://user-images.githubusercontent.com/16491181/33504404-ae265e00-d72a-11e7-99ab-f9116bede1c3.jpg)

**Comment by kura52** [comment]
I close this issue.
