### ISSUE TITLE
Installing redux devtools crx extension.

### ISSUE THREAD

**Issue by afonsoSoares** [kura52/sushi-browser#2]
Hi,
love your work done in this browser. Keep it up. Could you provide me a way to install redux devtools extension or more globally a chrome extension. I have download the .crx and try to open it with the browser but won't work. By the way I'm using Linux Mint. Thank you.

**Comment by kura52** [comment]
Thank you for raising this issue.  
First of all, I apologize that we cannot do support for redux devtools.   
Sushi browser uses the [muon](https://github.com/brave/muon) chrome extension support function (of Electron's fork through the Brave browser).  
Due to this, it becomes nearly equivalent to the support with chrome extension that is being supported by the [Brave Browser](https://github.com/brave/browser-laptop).   
The support status of the Brave chrome extension is posted [here](https://github.com/brave/browser-laptop/projects/1).  

It seems that React Developer Tool is in a pending status.   
Also, installation through crx is similarly has no support but if the [issue](https://github.com/brave/muon/issues/255) is resolved then it can be thought of as supported.   

It will be an irregularity but, the current install method of the chrome expansion is the following:
(There aren't that many extensions that can be used though...)  

1. Install the extension that you want to use in Google Chrome.
2. Copy the target extension ID at chrome://extensions/  
3. Using the Potable version Sushi Browser as an example, after file is decompressed, append the ID in 2. to resource/extensions.txt.
4. Restarting sushi browser copies the chrome extension target folder and the extension is read in. 

After restarting, if no particular error dialog appears, moreover, after right clicking the page, and selecting inspect element no error message appears in the console, then you can think that that extension is running correctly.

**Comment by afonsoSoares** [comment]
Ok thanks for the reply.
