### ISSUE TITLE
Run without Google Chrome but another Chromium? (e.g. Woolyss, Ungoogled?)

### ISSUE THREAD

**Issue by kowith337** [kura52/sushi-browser#66]
With new update, now your browser require me to install Google chrome, but I won't to (and probably never again) install it!

And your "Chrome bundle edition" is also exclude, however, I will keep it for test...

I want to use with another Chromium, **not "Google Chrome"**, e.g. I've often use and update Chromium from [Woolyss](https://chromium.woolyss.com), include [Ungoogled](https://github.com/macchrome/chromium/releases) one.

Any possible for that, at least argument to read chromium directory to another place rather than Google Chrome?

**Comment by kura52** [comment]
This can be done using the --browser-name and --browser-path arguments.

If Sushi Browser is placed in `C:\sushi-browser-portable` and Ungoogled is placed in `C:\Chrome-bin-79.0.3920.0`, execute the following command with cmd.

`
C:\sushi-browser-portable\sushi-browser.exe --browser-name="Chromium" --browser-path="C:\Chrome-bin-79.0.3920.0\chrome.exe"
`

*Because there was a problem with the previous version, please use [v27.0](https://github.com/kura52/sushi-browser/releases/tag/0.27.0).
